#!/usr/bin/env python3
"""Generate the German pages in /de/ from the English pages.

English pages are the source. Never edit /de/*.html by hand; edit the English
page (and tools/translations_de.py for the German wording), then run:

    python3 tools/build-de.py

The script also:
  * adds/refreshes the EN | DE switch and hreflang tags on the English pages
  * rebuilds sitemap.xml with both languages
  * reports English text without a German translation, and translations that
    are no longer used (usually because the English text changed)
Exit code 1 if anything is untranslated, so it can't be missed.
"""
import html
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from translations_de import NAV, TRANSLATIONS, SAME_IN_BOTH  # noqa: E402

PAGES = ["index", "dde", "advisory", "about", "insights", "contact"]
SITE = "https://carlberg-advisory.com/"
SHARED = ["impressum.html", "datenschutz.html"]  # German-only legal pages, used by both languages


def url(page, lang):
    path = "" if page == "index" else f"{page}.html"
    return SITE + ("de/" if lang == "de" else "") + path


def hreflang_block(page):
    return (f'  <link rel="alternate" hreflang="en" href="{url(page, "en")}">\n'
            f'  <link rel="alternate" hreflang="de" href="{url(page, "de")}">\n'
            f'  <link rel="alternate" hreflang="x-default" href="{url(page, "en")}">\n')


def switch(page, lang):
    f = f"{page}.html"
    if lang == "en":
        en, de, label = f, f"de/{f}", "Language"
    else:
        en, de, label = f"../{f}", f, "Sprache"
    cur_en = ' aria-current="true"' if lang == "en" else ""
    cur_de = ' aria-current="true"' if lang == "de" else ""
    return (f'<span class="lang-switch" role="group" aria-label="{label}">'
            f'<a href="{en}" hreflang="en" lang="en" aria-label="English"{cur_en}>EN</a>'
            f'<span aria-hidden="true">|</span>'
            f'<a href="{de}" hreflang="de" lang="de" aria-label="Deutsch"{cur_de}>DE</a></span>')


def ensure_english(page):
    """Make sure the English page has the language switch and hreflang tags."""
    path = os.path.join(ROOT, f"{page}.html")
    s = open(path, encoding="utf-8").read()
    orig = s
    s = re.sub(r'  <link rel="alternate" hreflang="[^"]+" href="[^"]+">\n', "", s)
    s = s.replace('  <link rel="icon"', hreflang_block(page) + '  <link rel="icon"', 1)
    s = re.sub(r'\s*<span class="lang-switch".*?</a></span>', "", s, flags=re.S)
    s = re.sub(r'(\n\s*)</nav>', r'\1  ' + switch(page, "en") + r'\1</nav>', s, count=1)
    if s != orig:
        open(path, "w", encoding="utf-8").write(s)
    return s


def to_german(page, s, used):
    s = s.replace('<html lang="en-GB">', '<html lang="de" data-root="../">', 1)
    # paths: German pages live one folder down
    s = s.replace('href="assets/', 'href="../assets/').replace('src="assets/', 'src="../assets/')
    for f in SHARED:
        s = s.replace(f'href="{f}"', f'href="../{f}"')
    s = s.replace('href="book/"', 'href="../book/"')
    # language switch
    s = re.sub(r'<span class="lang-switch".*?</a></span>', switch(page, "de"), s, flags=re.S)
    # menu labels (only inside the main nav)
    def nav(m):
        block = m.group(0)
        for p, label in NAV.items():
            block = re.sub(rf'(<a href="{p}\.html"(?: aria-current="page")?>)[^<]*(</a>)', rf'\g<1>{label}\g<2>', block)
        return block
    s = re.sub(r'<nav id="site-nav".*?</nav>', nav, s, flags=re.S)
    # text
    for en, de in sorted(TRANSLATIONS, key=lambda t: -len(t[0])):
        if en in s:
            s = s.replace(en, de)
            used.add(en)
    marker = (f"<!-- GENERATED from ../{page}.html by tools/build-de.py. Do not edit this file: "
              f"edit the English page and tools/translations_de.py, then run the script. -->\n")
    return s.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + marker, 1)


def visible_texts(s):
    """Text nodes and translatable attributes, normalised."""
    s = re.sub(r"<script.*?</script>|<style.*?</style>|<!--.*?-->", "", s, flags=re.S)
    out = set()
    for t in re.findall(r">([^<]+)<", s):
        t = " ".join(html.unescape(t).split())
        if t and not t.isspace():
            out.add(t)
    for t in re.findall(r'(?:content|aria-label|alt|title)="([^"]+)"', s):
        out.add(" ".join(html.unescape(t).split()))
    return out


def main():
    os.makedirs(os.path.join(ROOT, "de"), exist_ok=True)
    used, problems = set(), []
    for page in PAGES:
        en = ensure_english(page)
        de = to_german(page, en, used)
        open(os.path.join(ROOT, "de", f"{page}.html"), "w", encoding="utf-8").write(de)
        en_texts = visible_texts(re.sub(r"<head>.*?<title>|</title>.*?</head>", "", en, flags=re.S)) | visible_texts(en)
        left = sorted(t for t in visible_texts(de) & en_texts
                      if t not in SAME_IN_BOTH and not re.fullmatch(r"[\W\d_]+", t)
                      and not t.startswith(("http", "mailto:", "width=", "summary_", "website")))
        for t in left:
            problems.append(f"  {page}.html: untranslated: {t}")

    unused = [en for en, _ in TRANSLATIONS if en not in used]

    # sitemap
    rows = []
    for page in PAGES:
        for lang in ("en", "de"):
            rows.append(f"  <url>\n    <loc>{url(page, lang)}</loc>\n"
                        f'    <xhtml:link rel="alternate" hreflang="en" href="{url(page, "en")}"/>\n'
                        f'    <xhtml:link rel="alternate" hreflang="de" href="{url(page, "de")}"/>\n'
                        f"  </url>")
    open(os.path.join(ROOT, "sitemap.xml"), "w", encoding="utf-8").write(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
        + "\n".join(rows) + "\n</urlset>\n")

    print(f"Built {len(PAGES)} German pages in de/ and refreshed sitemap.xml.")
    if unused:
        print("\nTranslations no longer used (English text changed or removed?):")
        for en in unused:
            print("  -", en[:110])
    if problems:
        print("\nEnglish text without German translation:")
        print("\n".join(problems))
        sys.exit(1)
    print("All visible text is translated.")


if __name__ == "__main__":
    main()
